//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peephole
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenu
    {
        public int Id { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public string AreaName { get; set; }
        public string LinkText { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string URL { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
